# Generated by Django 3.2.3 on 2021-10-21 08:47

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('feed', '0002_auto_20211021_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationw',
            name='involved',
            field=taggit.managers.TaggableManager(help_text="Palabras Clave separadas por comas, mencione a Autoridades Competentes, Afectados o Zonas, tambien puede mencionarlos en la descripcion con el uso de Hashtag '#' y los espacios reemplazarlos por guion medio '-'", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Involucrados'),
        ),
    ]
