# Generated by Django 3.2.3 on 2021-10-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_publicationw_involved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=models.TextField(default='', help_text='Espacio de Libre Expresión', verbose_name='Escriba Aqui'),
        ),
        migrations.AlterField(
            model_name='publicationw',
            name='address',
            field=models.TextField(blank=True, default='Colombia', help_text="Pais, Departamento, Municipio, Vereda o Direccion exacta 'carrera #, calle #'", null=True, verbose_name='Escriba la Direccion o Ubicación de la Alerta'),
        ),
    ]
