# Generated by Django 3.2.3 on 2021-10-21 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20211021_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='img',
            field=models.ImageField(blank=True, help_text='.PNG, .JPG, .JPEG', null=True, upload_to='profile', verbose_name='Subir Imagen'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='img2',
            field=models.ImageField(blank=True, help_text='.PNG, .JPG, .JPEG', null=True, upload_to='profile/%Y', verbose_name='Subir Imagen'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='video',
            field=models.FileField(blank=True, help_text='Formato MP4', null=True, upload_to='profile/%Y', validators=[django.core.validators.FileExtensionValidator(['mp4'])], verbose_name='Subir Video'),
        ),
        migrations.AlterField(
            model_name='publicationw',
            name='img',
            field=models.ImageField(blank=True, help_text='.PNG, .JPG, .JPEG', null=True, upload_to='profile', verbose_name='Subir Imagen'),
        ),
        migrations.AlterField(
            model_name='publicationw',
            name='img2',
            field=models.ImageField(blank=True, help_text='.PNG, .JPG, .JPEG', null=True, upload_to='profile/%Y', verbose_name='Subir Imagen'),
        ),
        migrations.AlterField(
            model_name='publicationw',
            name='video',
            field=models.FileField(blank=True, help_text='Formato MP4', null=True, upload_to='profile/%Y', validators=[django.core.validators.FileExtensionValidator(['mp4'])], verbose_name='Subir Video'),
        ),
    ]
