# Generated by Django 3.2.3 on 2021-10-22 23:55

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20211021_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationw',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63),
        ),
    ]
