# Generated by Django 3.2.8 on 2021-10-23 01:53

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_alter_publicationw_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationw',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [0, 0], 'marker_color': 'blue'}),
        ),
    ]
