# Generated by Django 3.2.8 on 2021-10-23 02:17

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_rename_address_publicationw_addresss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationw',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [17.031645, 51.106715], 'marker_color': 'blue'}),
        ),
    ]
