# Generated by Django 3.2.8 on 2021-10-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_alter_publicationw_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationw',
            name='location',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
