# Generated by Django 3.2.8 on 2021-10-23 02:30

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_alter_publicationw_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationw',
            name='location',
        ),
        migrations.AddField(
            model_name='publicationw',
            name='locationmap',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [0, 0], 'marker_color': 'blue'}, null=True),
        ),
    ]
