# Generated by Django 3.2.8 on 2021-10-23 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_auto_20211023_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationw',
            name='locationmap',
        ),
    ]
