# Generated by Django 3.2.8 on 2021-10-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_auto_20211025_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationw',
            name='empty_img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicationw',
            name='empty_img2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicationw',
            name='empty_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicationw',
            name='empty_video',
            field=models.BooleanField(default=False),
        ),
    ]
