# Generated by Django 3.2.8 on 2021-10-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_auto_20211025_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='tag_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publicationw',
            name='tag_text',
            field=models.TextField(blank=True),
        ),
    ]
