# Generated by Django 3.2.8 on 2021-10-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_auto_20211025_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationw',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
