# Generated by Django 3.2.8 on 2021-10-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_publicationw_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationw',
            name='category',
            field=models.TextField(blank=True, choices=[(11, 'Credit Card'), (12, 'Student Loans'), (13, 'Taxes'), (21, 'Books'), (22, 'Games'), (31, 'Groceries'), (32, 'Restaurants')]),
        ),
    ]
