# Generated by Django 3.2.8 on 2021-10-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0022_alter_publicationw_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationw',
            name='category',
            field=models.TextField(blank=True, choices=[('Desaparición', 'Desaparición'), ('DesplazamientoForzado', 'Desplazamiento Forzado'), ('PresenciaGruposArmados', 'Presencia Grupos Armados'), ('ViolenciaPolicial', 'Violencia Policial'), ('MaltratoIntrafamiliar', 'Maltrato Intrafamiliar'), ('ViolenciaDeGenero', 'Violencia de Genero'), ('ViolenciaSexual', 'Violencia Sexual'), ('ExploacionLaboral', 'Explotación Laboral'), ('Corrupcion', 'Corrupción'), ('MaltratoAnimal', 'Maltrato Animal'), ('Deforestacion', 'Deforestación'), ('ContaminacionAmbiental', 'Contaminación Ambiental')]),
        ),
    ]
