# Generated by Django 3.2.8 on 2021-10-31 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0025_auto_20211031_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='feed.publication'),
        ),
    ]
