# Generated by Django 3.2.8 on 2021-11-01 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0028_auto_20211031_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='publicationw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feed.publicationw'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feed.publication'),
        ),
    ]
