# Generated by Django 3.2.8 on 2021-11-03 01:11

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0030_auto_20211101_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationw',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Desaparicion', 'Desaparición'), ('DesplazamientoForzado', 'Desplazamiento Forzado'), ('PresenciaGruposArmados', 'Presencia Grupos Armados'), ('AbusoPolicial', 'AbusoPolicial'), ('Extorsion', 'Extorsión'), ('Estafa', 'Estafa'), ('Deforestacion', 'Deforestación'), ('MaltratoIntrafamiliar', 'Maltrato Intrafamiliar'), ('ViolenciaDeGenero', 'Violencia de Genero'), ('ViolenciaSexual', 'Violencia Sexual'), ('Discriminacion', 'Discriminación'), ('ExplotacionLaboral', 'Explotación Laboral'), ('Corrupcion', 'Corrupción'), ('MaltratoAnimal', 'Maltrato Animal'), ('Deforestacion', 'Deforestación'), ('ContaminacionAmbiental', 'Contaminación Ambiental')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publicationw',
            name='case_id',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='publicationw',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='publicationw',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='publicationw',
            name='lon',
            field=models.FloatField(default=0),
        ),
    ]
