# Generated by Django 3.2.8 on 2021-11-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0033_auto_20211104_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='updatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commentsw',
            name='updatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='updatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationw',
            name='mapaddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationw',
            name='updatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
